services:
  - type: web
    name: santander-dev
    env: docker
    buildCommand: ./gradlew clean build
    startCommand: java -jar build/libs/santander-dev-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromSecret: SPRING_DATASOURCE_URL
      - key: SPRING_DATASOURCE_USERNAME
        fromSecret: SPRING_DATASOURCE_USERNAME
      - key: SPRING_DATASOURCE_PASSWORD
        fromSecret: SPRING_DATASOURCE_PASSWORD
    buildpacks:
      - heroku/java